export default {
  event: {
    eventList: "event/search",
    eventDetail: "event/details",
    registerEvent: "user/event-member/register",
    cancelRegisterEvent: "user/event-member/cancel",
    createEvent: "event/create",
    organizerRegisterEvent: "user/organizer/register",
    cancelOrganizerRegisterEvent: "user/organizer/cancel",
    editEvent: "event/edit",
    cancelEvent: "event/cancel",
    listMemberRegister: "event/details/members",
    getTagArea: "event/tag/areas",
    getTagPurpose: "event/tag/purposes",
  },
  user: {
    getProfile: "user/profile",
    userRegister: "user/register",
    userRegisterVerify: "user/register/confirm",
    login: "user/login",
    terms: "user/terms",
    forgotPassword: "user/password/forgot",
    resetPassword: "user/password/reset",
    passwordCheckResetToken: "user/password/check-reset-token",
    registerResendEmail: "user/register/resend",
  },
  uploadImage: "upload/images",
  updateInformation: "user/update-information",
  withdraw: "user/withdraw",
  getPrefecture: "user/prefecture/list",
};
